<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\longbow\\example\\applicationconfiguration' => '/exampleApplication/ApplicationConfiguration.php',
                'spriebsch\\longbow\\example\\applicationfactory' => '/exampleApplication/ApplicationFactory.php',
                'spriebsch\\longbow\\example\\somecommand' => '/exampleApplication/SomeCommand.php',
                'spriebsch\\longbow\\example\\somecommandhandler' => '/exampleApplication/SomeCommandHandler.php',
                'spriebsch\\longbow\\example\\someevent' => '/exampleApplication/SomeEvent.php',
                'spriebsch\\longbow\\example\\someeventhandler' => '/exampleApplication/SomeEventHandler.php',
                'spriebsch\\longbow\\example\\someeventstream' => '/exampleApplication/SomeEventStream.php',
                'spriebsch\\longbow\\example\\someeventstreamprocessor' => '/exampleApplication/SomeEventStreamProcessor.php',
                'spriebsch\\longbow\\example\\someid' => '/exampleApplication/SomeId.php',
                'spriebsch\\longbow\\example\\something' => '/exampleApplication/Something.php',
                'spriebsch\\longbow\\example\\something2' => '/exampleApplication/Something2.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
