<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\longbow\\tests\\testcommand' => '/../stubs/TestCommand.php',
                'spriebsch\\longbow\\tests\\testcommandhandlerfactory' => '/../stubs/TestCommandHandlerFactory.php',
                'spriebsch\\longbow\\tests\\testcommandhandlerthatreturnsevent' => '/../stubs/TestCommandHandlerThatReturnsEvent.php',
                'spriebsch\\longbow\\tests\\testcommandhandlerthatthrowsexception' => '/../stubs/TestCommandHandlerThatThrowsException.php',
                'spriebsch\\longbow\\tests\\testcorrelationid' => '/../stubs/TestCorrelationId.php',
                'spriebsch\\longbow\\tests\\testevent' => '/../stubs/TestEvent.php',
                'spriebsch\\longbow\\tests\\testeventhandler' => '/../stubs/TestEventHandler.php',
                'spriebsch\\longbow\\tests\\testeventhandlerfactory' => '/../stubs/TestEventHandlerFactory.php',
                'spriebsch\\longbow\\tests\\testeventstream' => '/../stubs/TestEventStream.php',
                'spriebsch\\longbow\\tests\\testeventstreamprocessor' => '/../stubs/TestEventStreamProcessor.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
